openapi: 3.0.1
info:
  title: Gmail Sender API
  description: An API to send email via Gmail using n8n
  version: 1.0.0
paths:
  /send-email:
    post:
      operationId: sendEmail
      summary: Send an email using Gmail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                to:
                  type: string
                  description: Recipient's email address
                subject:
                  type: string
                  description: Subject of the email
                body:
                  type: string
                  description: Body of the email
      responses:
        '200':
          description: Email sent successfully
        '400':
          description: Bad request
servers:
  - url: https://n8n.srv822834.hstgr.cloud/mcp/ea3a5764-40ab-4ac1-a365-f7b157ee9955/sse
